 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/contatos", type: :request do
  
  # Contato. As you add validations to Contato, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Contato.create! valid_attributes
      get contatos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      contato = Contato.create! valid_attributes
      get contato_url(contato)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_contato_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      contato = Contato.create! valid_attributes
      get edit_contato_url(contato)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Contato" do
        expect {
          post contatos_url, params: { contato: valid_attributes }
        }.to change(Contato, :count).by(1)
      end

      it "redirects to the created contato" do
        post contatos_url, params: { contato: valid_attributes }
        expect(response).to redirect_to(contato_url(Contato.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Contato" do
        expect {
          post contatos_url, params: { contato: invalid_attributes }
        }.to change(Contato, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post contatos_url, params: { contato: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested contato" do
        contato = Contato.create! valid_attributes
        patch contato_url(contato), params: { contato: new_attributes }
        contato.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the contato" do
        contato = Contato.create! valid_attributes
        patch contato_url(contato), params: { contato: new_attributes }
        contato.reload
        expect(response).to redirect_to(contato_url(contato))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        contato = Contato.create! valid_attributes
        patch contato_url(contato), params: { contato: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested contato" do
      contato = Contato.create! valid_attributes
      expect {
        delete contato_url(contato)
      }.to change(Contato, :count).by(-1)
    end

    it "redirects to the contatos list" do
      contato = Contato.create! valid_attributes
      delete contato_url(contato)
      expect(response).to redirect_to(contatos_url)
    end
  end
end
